name: Generate and Push Cover Images

on:
  push:
    paths:
      - '**/*.md'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
  generate_cover_images:
    runs-on: ubuntu-latest
    if: |
      github.event.head_commit.message != 'Updating Covers and Deploying'
        && !contains(github.event.head_commit.message, 'Merge remote-tracking branch')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system pillow ruamel.yaml PyGithub

      - name: Run Script
        run: |
          ls -l .github/scripts
          python .github/scripts/generate_cover_images.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
